---
# Main playbook for Ubuntu Noble environment (ALL hosts)
- name: Bootstrap Ubuntu Noble with ttdaiu
  hosts: all
  become: yes
  vars:
    main_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
    main_home: "{{ '/home/' + (ansible_env.SUDO_USER | default(ansible_user_id)) }}"

  pre_tasks:


    - name: Verify Ubuntu version compatibility
      ansible.builtin.assert:
        that:
          - ansible_distribution == "Ubuntu"
          - ansible_distribution_version is version('24.04', '==')
        fail_msg: "This playbook is designed for Ubuntu 24.04 (Noble Numbat)"

    - name: Apt | update cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

  roles:
    - role: backup
      tags: [backup, base]

    - role: packages
      tags: [packages, base]

    - role: bash
      tags: [bash, base]

    - role: libvirt
      tags: [libvirt, full]

    - role: nginx
      tags: [nginx, full]

    - role: z80
      tags: [z80, full]

    - role: github
      tags: [github, full]

    - role: chromium
      tags: [chromium, snap, full]

    - role: code
      tags: [code, snap, full]

    - role: codium
      tags: [codium, snap, full]

    - role: docker
      tags: [docker, full]

    - role: golang
      tags: [golang, snap, full]

    - role: libreoffice
      tags: [libreoffice, snap, full]

    - role: node
      tags: [node, iacode, snap, full]

    - role: codex
      tags: [codex, iacode, npm, full]

    - role: claude
      tags: [claude, iacode, npm, full]

    - role: gemini
      tags: [gemini, iacode, npm, full]

    - role: opencode
      tags: [opencode, iacode, npm, full]
