---
# Main playbook for Vagrant environment (ALL hosts)
- name: Bootstrap Ubuntu Noble with ttdaiu
  hosts: all
  become: yes
  vars:
    main_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
    main_home: "{{ '/home/' + (ansible_env.SUDO_USER | default(ansible_user_id)) }}"

  pre_tasks:
    - name: Define Vagrant/VM environment flag
      ansible.builtin.set_fact:
        is_vagrant: >-
          {{ (ansible_virtualization_type in ['kvm','virtualbox'])
            or (ansible_product_name|lower is search('virtualbox'))
            or (ansible_system_vendor|lower is search('qemu|kvm')) }}

    - name: Apt | update cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

  roles:
    - { role: backup,      tags: [backup] }
    - { role: packages,    tags: [packages] }

    - { role: bash,        tags: [bash] }
    - { role: libvirt,     tags: [libvirt] }
    - { role: nginx,       tags: [nginx] }
    - { role: z80,         tags: [z80] }
    - { role: github,      tags: [github] }

    - { role: chromium,    tags: [snap, chromium] }
    - { role: code,        tags: [snap, code] }
    - { role: codium,      tags: [snap, codium] }
    - { role: docker,      tags: [snap, docker] }
    - { role: golang,      tags: [snap, golang] }
    - { role: libreoffice, tags: [snap, libreoffice] }
    - { role: node,        tags: [snap, node] }
