Vagrant.configure("2") do |config|
  config.vm.box = "cloud-image/ubuntu-24.04"

#  config.ssh.insert_key = false

  config.vm.network :private_network,
    type: "dhcp",
    libvirt__network_name:    "nat50",
    libvirt__network_address: "192.168.50.0",
    libvirt__netmask:         "255.255.255.0",
    libvirt__domain_name:     "lab.local",
    libvirt__dhcp_enabled:    true,
    libvirt__dhcp_start:      "192.168.50.2",
    libvirt__dhcp_stop:       "192.168.50.254",
    autostart:                true

  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 4096
    libvirt.cpus   = 1
    libvirt.driver = "kvm"
    libvirt.uri    = "qemu:///system"
  end

  config.vm.hostname = "ttdaiu"

  config.vm.provision :ansible do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook           = "noble.yml"
    ansible.become             = true
    ansible.limit              = "default"
  end
end
