---
- copy:
    src: bash_aliases.sh
    dest: /home/carlos/.bash_aliases
    owner: carlos
    group: carlos
    mode: u+rw,g+r

- copy:
    src: bash_extras.sh
    dest: /home/carlos/.bash_extras
    owner: carlos
    group: carlos
    mode: u+rw,g+r

- copy:
    src: bashrc.sh
    dest: /home/carlos/.bashrc
    owner: carlos
    group: carlos
    mode: u+rw,g+r

- copy:
    src: profile.sh
    dest: /home/carlos/.profile
    owner: carlos
    group: carlos
    mode: u+rw,g+r
