---
- hosts: localhost
  connection: local
  become: yes
  roles:
    - {role: apt, tags: [apt, wsl] }
    - {role: aptx, tags: [apt] }
    - {role: google-chrome, tags: [google-chrome] }
    - {role: microsoft-edge, tags: [microsoft-edge] }
    - {role: docker, tags: [docker] }
    - {role: godot, tags: [godot] }
    - {role: golang, tags: [golang] }
    - {role: k3d, tags: [k3d, wsl] }
    - {role: kubectl, tags: [kubectl, wsl] }
    - {role: hashicorp, tags: [hashicorp, wsl] }
    - {role: code, tags: [code, wsl] }
    - {role: z80, tags: [z80, wsl] }
    - {role: godot, tags: [godot] }
