---
- file:
    path: /usr/share/keyrings/kubernetes-archive-keyring.gpg
    state: absent

- file:
    path: /usr/share/keyrings/kubernetes-apt-keyring.gpg
    state: absent

- apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
    keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    state: present

- apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /
    filename: kubernetes
    state: present

- apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - kubectl
    state: present
    update_cache: true
