---
# Package management tasks focused on reliable, sequential execution

- name: Check if apt-fast is available
  ansible.builtin.command: which apt-fast
  register: apt_fast_check
  failed_when: false
  changed_when: false
  tags: [performance, optimization]

- name: Install apt-fast when requested
  ansible.builtin.apt:
    pkg: apt-fast
    state: present
    update_cache: true
  when:
    - use_apt_fast | default(false)
    - apt_fast_check.rc != 0
  tags: [performance, optimization]

- name: Update package cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time | default(3600) }}"
  register: apt_update_result
  retries: 3
  delay: 10
  until: apt_update_result is succeeded
  tags: [system, update]

- name: Perform system upgrade
  ansible.builtin.apt:
    upgrade: "{{ apt_upgrade_type | default('dist') }}"
  register: apt_upgrade_result
  retries: 2
  delay: 30
  until: apt_upgrade_result is succeeded
  when:
    - apt_upgrade_type is defined
    - not ansible_check_mode
  tags: [system, upgrade]

- name: Install development packages
  ansible.builtin.apt:
    pkg: "{{ development_packages }}"
    state: present
  register: dev_packages_result
  retries: 2
  delay: 10
  until: dev_packages_result is succeeded
  when: development_packages | length > 0
  tags: [development, packages]

- name: Install network packages
  ansible.builtin.apt:
    pkg: "{{ network_packages }}"
    state: present
  register: network_packages_result
  retries: 2
  delay: 10
  until: network_packages_result is succeeded
  when: network_packages | length > 0
  tags: [network, packages]

- name: Install media packages
  ansible.builtin.apt:
    pkg: "{{ media_packages }}"
    state: present
  register: media_packages_result
  retries: 2
  delay: 15
  until: media_packages_result is succeeded
  when: media_packages | length > 0
  tags: [media, packages]

- name: Install graphics packages
  ansible.builtin.apt:
    pkg: "{{ graphics_packages }}"
    state: present
  register: graphics_packages_result
  retries: 2
  delay: 10
  until: graphics_packages_result is succeeded
  when: graphics_packages | length > 0
  tags: [graphics, packages]

- name: Install productivity packages
  ansible.builtin.apt:
    pkg: "{{ productivity_packages }}"
    state: present
  register: productivity_packages_result
  retries: 2
  delay: 10
  until: productivity_packages_result is succeeded
  when: productivity_packages | length > 0
  tags: [productivity, packages]

- name: Install LaTeX packages
  ansible.builtin.apt:
    pkg: "{{ latex_packages }}"
    state: present
  register: latex_packages_result
  retries: 2
  delay: 20
  until: latex_packages_result is succeeded
  when: latex_packages | length > 0
  tags: [latex, packages]

- name: Install system utilities
  ansible.builtin.apt:
    pkg: "{{ system_utilities }}"
    state: present
  register: system_utilities_result
  retries: 2
  delay: 10
  until: system_utilities_result is succeeded
  when: system_utilities | length > 0
  tags: [utilities, packages]

- name: Clean package cache
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
  when:
    - apt_clean_cache | default(true)
    - not ansible_check_mode
  tags: [cleanup, optimization]
