---
- apt:
    pkg:
      - abntex
      - autoconf
      - automake
      - black
      - bleachbit
      - build-essential
      - chromium-browser
      - curl
      - default-jdk
      - default-jre
      - ffmpeg
      - filezilla
      - firefox
      - g++
      - gimp
      - git
      - gnome-tweaks
      - gradle
      - gufw
      - hugo
      - imagemagick
      - inkscape
      - jekyll
      - libcurl4-openssl-dev
      - libgmp-dev
      - libjansson-dev
      - libreoffice
      - libsdl2-dev
      - libsdl2-gfx-dev
      - libsdl2-image-dev
      - libsdl2-mixer-dev
      - libsdl2-net-dev
      - libsdl2-ttf-dev
      - libssl-dev
      - lmms
      - love
      - make
      - mc
      - meld
      - mypaint
      - net-tools
      - network-manager-l2tp
      - network-manager-l2tp-gnome
      - network-manager-openconnect
      - network-manager-openconnect-gnome
      - obs-studio
      - openssh-server
      - pep8
      - php-cli
      - php-gd
      - php-imagick
      - php-mysql
      - php-snmp
      - pkg-config
      - postgresql-client
      - preload
      - python3-dev
      - python3-pip
      - python3-pylint-celery
      - python3-pylint-django
      - python3-pylint-flask
      - python3-pylint-plugin-utils
      - python3-virtualenv
      - python-is-python3
      - remmina
      - ssh-askpass
      - sshpass
      - texlive
      - texlive-lang-portuguese
      - texlive-latex-extra
      - texlive-publishers
      - texstudio
      - texstudio-doc
      - texstudio-l10n
      - virtualbox
      - vlc
      - yadm
      - zlib1g-dev
    state: present
