---
- apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /usr/share/keyrings/microsoft-keyring.gpg
    state: present

- apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main
    filename: microsoft-edge-beta
    state: present

- apt:
    pkg:
      - microsoft-edge-beta
    state: present
    update_cache: true
