---
- get_url:
    url: https://raw.githubusercontent.com/rancher/k3d/main/install.sh
    dest: /tmp/install.sh
    mode: u+x,g-x

- shell:
    cmd: bash /tmp/install.sh

- file:
    path: /tmp/install.sh
    state: absent
