---
- apt:
    pkg:
      - audacity
      - bleachbit
      - chromium-browser
      - filezilla
      - firefox
      - gimp
      - gnome-tweaks
      - inkscape
      - lmms
      - love
      - meld
      - mypaint
      - network-manager-l2tp
      - network-manager-l2tp-gnome
      - network-manager-openconnect
      - network-manager-openconnect-gnome
      - openssh-server
      - remmina
      - texlive
      - texlive-lang-portuguese
      - texlive-latex-extra
      - texlive-publishers
      - texstudio
      - texstudio-doc
      - texstudio-l10n
      - virtualbox
      - vlc
    state: present
