---
- name: Check if @google/gemini-cli is installed globally
  become: true
  ansible.builtin.command: npm list -g @google/gemini-cli --depth=0
  environment:
    PATH: "/snap/bin:{{ ansible_env.PATH }}"
  register: gemini_npm_installed
  failed_when: gemini_npm_installed.rc not in [0, 1]
  changed_when: false

- name: Install @google/gemini-cli globally
  become: true
  ansible.builtin.command: npm install -g @google/gemini-cli
  environment:
    PATH: "/snap/bin:{{ ansible_env.PATH }}"
  when: gemini_npm_installed.rc == 1
