---
- name: Install @google/gemini-cli (latest)
  become: true
  ansible.builtin.command: npm install -g @google/gemini-cli@latest
  environment:
    PATH: "/snap/bin:{{ ansible_env.PATH }}"
  register: gemini_install
  changed_when: gemini_install.rc == 0
  when: not ansible_check_mode
