---
- name: Install @anthropic-ai/claude-code (latest)
  become: true
  ansible.builtin.command: npm install -g @anthropic-ai/claude-code@latest
  environment:
    PATH: "/snap/bin:{{ ansible_env.PATH }}"
  register: claude_install
  changed_when: claude_install.rc == 0
  when: not ansible_check_mode
