Vagrant.configure("2") do |config|

  config.vm.box="ubuntu/focal64"

  config.ssh.insert_key=false

  config.vm.provider :virtualbox do |vb|
    vb.name="ttdaiu"
    vb.memory="4096"
    vb.cpus="2"
  end

  config.vm.hostname="ttdaiu"
  config.vm.network :private_network, ip: "192.168.56.11"

  config.vm.define :ttdaiu do |ttdaiu|
  end

  config.vm.provision :ansible do |ansible|
    ansible.compatibility_mode="2.0"
    ansible.playbook="focal.yml"
    ansible.inventory_path="inventory/hosts"
    ansible.become=true
  end

end
