---
- name: Install opencode-ai (latest)
  become: true
  ansible.builtin.command: npm install -g opencode-ai@latest
  environment:
    PATH: "/snap/bin:{{ ansible_env.PATH }}"
  register: opencode_install
  changed_when: opencode_install.rc == 0
  when: not ansible_check_mode
