Vagrant.configure("2") do |config|

  config.vm.box = "cloud-image/ubuntu-24.04"

  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 2048
    libvirt.cpus   = 4
    libvirt.driver = "kvm"
    libvirt.uri    = "qemu:///system"
  end

  config.vm.hostname = "ttdaiu"

  config.vm.provision :ansible do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook           = "noble.yml"
    ansible.become             = true
    ansible.limit              = "default"
  end

end
