---
- apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    keyring: /usr/share/keyrings/google-chrome-keyring.gpg
    state: present

- apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main
    filename: google-chrome
    state: present

- apt:
    pkg:
      - google-chrome-stable
    state: present
    update_cache: true