name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: make install-deps
      - name: Check syntax
        run: make check
      - name: Dry-run test (default noble)
        run: make dry-run